export const APP_CONFIG = {
  // BASE_URL: "https://e-commerce-electronics-server.vercel.app/api/",
  API_URL: "http://192.168.1.229:5001",
  BASE_URL: "http://192.168.1.229:5001/api/",
  // BASE_URL: "https://25d9112fc9b8d9a7c359538eb017bf6d.serveo.net/api/",
};

export const QUERY_KEYS = {
  GET_CART: "GET_CART",
  GET_CURRENT_USER: "GET_CURRENT_USER",
  GET_ALL_PRODUCT: "GET_ALL_PRODUCT",
  GET_MESSAGE: "GET_MESSAGE",
  GET_ORDER_BY_ID: "GET_ORDER_BY_ID",
  USER_ADDRESSES: "USER_ADDRESSES",
  GET_POPULAR_PRODUCTS: "GET_POPULAR_PRODUCTS",
  GET_LATEST_PRODUCTS: "GET_LATEST_PRODUCTS",
  GET_SPECIAL_PRODUCTS: "GET_SPECIAL_PRODUCTS",
  GET_BLOGS: "GET_BLOGS",
  GET_MY_ORDER: "GET_MY_ORDER",
};

export const MUTAION_KEYS = {
  CREATE_ORDER: "CREATE_ORDER",
  PURCHASE: "PURCHASE",
  PURCHASE_SUCCESS: "PURCHASE_SUCCESS",
  ADD_TO_CART: "ADD_TO_CART",
  SET_DEFAULT_ADDRESS: "SET_DEFAULT_ADDRESS",
  UPDATE_ADDRESS: "UPDATE_ADDRESS",
  DELETE_ADDRESS: "DELETE_ADDRESS",
  SAVE_ADDRESS: "SAVE_ADDRESS",
  UPDATE_USER: "UPDATE_USER",
  SEND_MESSAGE: "SEND_MESSAGE",
  CANCEL_ORDER: "CANCEL_ORDER",
  DELETE_USER: "DELETE_USER",
  REORDER_ORDER: "REORDER_ORDER",
  DELETE_PRODUCT_FROM_CART: "DELETE_PRODUCT_FROM_CART",
  UPDATE_PRODUCT_RATING: "UPDATE_PRODUCT_RATING",
  EMPTY_CART: "EMPTY_CART",
  CALCULATE_SHIPPING_FEE: "CALCULATE_SHIPPING_FEE",
};

export const PURCHASE_RESPONSE = {
  success: "https://www.w3schools.com/",
  cancel: "https://www.google.com/",
};
