export const APP_CONFIG = {
  // BASE_URL: "https://e-commerce-electronics-server.vercel.app/api/",
  API_URL: "http://192.168.1.12",
  BASE_URL: "http://192.168.1.12:5001/api/",
  // BASE_URL: "https://25d9112fc9b8d9a7c359538eb017bf6d.serveo.net/api/",
};

export const QUERY_KEYS = {
  GET_CART: "GET_CART",
  GET_CURRENT_USER: "GET_CURRENT_USER",
  GET_ALL_PRODUCT: "GET_ALL_PRODUCT",
  GET_MESSAGE: "GET_MESSAGE",
  GET_ORDER_BY_ID: "GET_ORDER_BY_ID",
  USER_ADDRESSES: "USER_ADDRESSES",
  GET_POPULAR_PRODUCTS: "GET_POPULAR_PRODUCTS",
  GET_LATEST_PRODUCTS: "GET_LATEST_PRODUCTS",
  GET_SPECIAL_PRODUCTS: "GET_SPECIAL_PRODUCTS",
};

export const MUTAION_KEYS = {
  CREATE_ORDER: "CREATE_ORDER",
  PURCHASE: "PURCHASE",
  PURCHASE_SUCCESS: "PURCHASE_SUCCESS",
  ADD_TO_CART: "ADD_TO_CART",
  SET_DEFAULT_ADDRESS: "SET_DEFAULT_ADDRESS",
  UPDATE_ADDRESS: "UPDATE_ADDRESS",
  DELETE_ADDRESS: "DELETE_ADDRESS",
  SAVE_ADDRESS: "SAVE_ADDRESS",
  UPDATE_USER: "UPDATE_USER",
  SEND_MESSAGE: "SEND_MESSAGE",
};

export const PURCHASE_RESPONSE = {
  success: "https://www.w3schools.com/",
  cancel: "https://www.google.com/",
};
